#!/bin/sh
# Write/remove a task to do later.

read -r file || exit 0
TASKFILE="$XDG_CACHE_HOME/todo/$file"

while true; do
	result=`dmenu -p "Add new task or toggle" < "$TASKFILE"`
	sub=`printf "$result" | sed -e 's/( )/(x)/' -e t -e 's/(x)/( )/' -e t`
	# Return to main program on exit
	test -z "$result" && exec todo
	case $result in
		\(\ \)*) sed -i "s:$result:$sub:g" "$TASKFILE" ;;
		\(x\)*)  sed -i "s:$result:$sub:g" "$TASKFILE" ;;
		*)       printf '%s\n' "( ) $result" >> "$TASKFILE" ;;
	esac
done
