#!/bin/sh
todir="$XDG_CACHE_HOME/todo"

# If we have data on stdin, use it
test -p /dev/stdin && exec /usr/local/share/todo/singletask < /dev/stdin 

load() {
	ls "$todir" | while read -r title; do		
		match="$(grep -c "(x)" "$todir/$title")"
		# Calculate percentage of lines with completed tasks
		total="$(wc -l "$todir/$title" | awk '{ print "100*'$match'/" $1 }' | bc)"
		printf '%.2d%% - %s\n' "$total" "$title"
	done
}

# Narrow by selection and open in single task handler
load | sort -r | dmenu -p "Select/create task" | sed 's/.* - //' | /usr/local/share/todo/singletask
