#!/bin/sh
# Write/remove a task to do later.

todir="$XDG_CACHE_HOME/todo"
load() {
	# count matches with grep vs line count
  	cd "$todir" || exit 1
	find ./ \! -path '*/\.*' \! -name 'singletask' -type f | while read -r title; do
		if ! test -s "$title"; then
			rm "$title"
			continue
		fi
		match="`grep -c "(x)" "$title"`"
		total="`wc -l "$title" | awk '{ print "100*'$match'/" $1 }' | bc`"
		printf '%.2d%% - %s\n' "$total" "`basename "$title"`"
	done
}

## Main
load | sort -r | dmenu -p "Select/create task" | sed 's/.* - //' | /usr/local/share/todo/singletask
